pool:
  vmImage: 'ubuntu-18.04'

parameters:
  - name: skipTests
    type: boolean
    default: false

resources:
  repositories:
    - repository: infra-repo
      type: git
      name: infrastructure

stages:
  - stage: BuildTestAndPackage
    jobs:
      - job: MavenAndDocker
        steps:
          - template: az/pipeline/maven-and-docker.yaml@infra-repo
            parameters:
              projectDir: $(System.DefaultWorkingDirectory)
              mavenGoals: deploy
              additionalMavenOptions: -DskipTests=${{parameters.skipTests}}
              containerRepository: smarthub-server-$(Build.SourceBranchName)