trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
variables:
  containerRegistryServiceConnection: azure-gocompliant
  imageRepository: smarthub-mockserver
  tag: 1.0.2

stages:
- stage: Build
  jobs:
  - job: Maven
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'package'
        jdkVersion: '1.11'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        publishJUnitResults: false
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - publish: $(System.DefaultWorkingDirectory)/mockserver
      artifact: mockserver
