version: "3.8"
services:
  ai-log4j-reproducer:
    image: ai-log4j-reproducer-local
    build:
      context: ./..
      dockerfile: infra/Dockerfile
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: >-
        -Xmx1g -Xms1g -verbose:gc
        -javaagent:/mnt/ai/applicationinsights-agent-3.0.0.jar
#        -DLog4jContextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector
      APPLICATIONINSIGHTS_CONFIGURATION_FILE: /mnt/ai/ai-config.json
      APPLICATIONINSIGHTS_ROLE_NAME: reproducer
      APPINSIGHTS_INSTRUMENTATIONKEY: #-#-#-#-#
    volumes:
    - ./ai-config.json:/mnt/ai/ai-config.json
    - ./applicationinsights-agent-3.0.0.jar:/mnt/ai/applicationinsights-agent-3.0.0.jar