trigger: none

pool:
  vmImage: 'ubuntu-18.04'

parameters:
  - name: skipTests
    type: boolean
    default: false

resources:
  repositories:
    - repository: infa-repo
      type: git
      name: infrastructure

jobs:
  - template: az/pipeline/release-with-docker.yaml@infa-repo
    parameters:
      additionalMavenOptions: -DskipTests=${{parameters.skipTests}}
      containerRepository: mockservice-server