trigger: none

pool:
  vmImage: 'ubuntu-20.04'

variables:
  version: ''
  localMavenSettingFile: '../maven-settings.xml'

steps:
  - task: MavenAuthenticate@0
    inputs:
      artifactsFeeds: 'product-release'
  - bash: |
        #!/bin/bash
        touch $(localMavenSettingFile)
        echo '<settings>' >> $(localMavenSettingFile)
        echo '  <servers>' >> $(localMavenSettingFile)
        echo '      <server>' >> $(localMavenSettingFile)
        echo '          <id>az-goco-git</id>' >> $(localMavenSettingFile)
        echo '          <username>daniel.varga</username>' >> $(localMavenSettingFile)
        echo '          <password>rvzhopxksen67chkvlgzybkwl6ytxgetpwopbrpjax4guckkmdaq</password>' >> $(localMavenSettingFile)
        echo '      </server>' >> $(localMavenSettingFile)
        echo '  </servers>' >> $(localMavenSettingFile)
        echo '</settings>' >> $(localMavenSettingFile)
        cat $(localMavenSettingFile)
    displayName: 'Write $(localMavenSettingFile)'
  - task: Maven@3
    displayName: 'mvn releaser:release'
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'releaser:release'
      options: '-DserverId=az-goco-git -gs $(localMavenSettingFile) '
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false  
  - bash: |
      #!/bin/bash
      cat ./target/maven-archiver/pom.properties
      set -a
      . ./target/maven-archiver/pom.properties
      set +a
      echo "##vso[task.setvariable variable=groupId;]$groupId"
      echo "##vso[task.setvariable variable=artifactId;]$artifactId"
      echo "##vso[task.setvariable variable=version;]$version"
    displayName: 'export pom properties'
  - bash: |
      #!/bin/bash
      echo "##vso[build.updatebuildnumber]$(version)"
    displayName: 'update release name'
  - task: Docker@2
    displayName: buildAndPush
    inputs:
      containerRegistry: 'gocompliant-container-registry'
      repository: 'mockservice-server'
      Dockerfile: '$(System.DefaultWorkingDirectory)/infra/Dockerfile'
      buildContext: '$(System.DefaultWorkingDirectory)'
      tags: '$(version)'