trigger: none

pool:
  vmImage: 'ubuntu-18.04'

resources:
  repositories:
    - repository: infa-repo
      type: git
      name: infrastructure

jobs:
  - template: az/pipeline/release-with-docker.yaml@infa-repo